import Head from 'next/head'
import Image from 'next/image'
import styles from './index.module.scss'
import {getList} from "@/api";

// 引入 长列表优化组件
import 'react-virtualized/styles.css';

import {Grid, WindowScroller} from 'react-virtualized';
import {useEffect, useRef, useState} from "react";

export default function Home(props: any) {
  const [data, setData] = useState<any>([])
  console.log(props)
  const {list = []} = props.data
  //
  for (let i = 0; i < props.data.list.length; i += 5) {
    data.push(props.data.list.slice(i, i + 5))
  }
  //
  // useEffect(() => {
  //   getList({page: ref.current.page}).then(res => {
  //     const result = []
  //     for (let i = 0; i < res.data.list.length; i += 5) {
  //       result.push(res.data.list.slice(i, i + 5))
  //     }
  //     setData(result)
  //   })
  // }, [])

  const cellRenderer = ({columnIndex, key, rowIndex, style}: any) => {
    const item = data[rowIndex][columnIndex]

    return (
      <div key={key} style={style}>
        <div key={item.detail_url_alias} className={styles.list_item}>
          <Image width={241} height={161} src={item.thuimg324} alt={item.res_name}/>
          <p className={styles.list_info}>
            <span>{item.res_name}</span>
            <span>{item.res_price}下载币</span>
          </p>
        </div>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>3D66</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <header className={styles.header}>
        <Image src={require('@/img/header.png')} alt="头部"></Image>
      </header>
      <main className={styles.main}>
        <div className={styles.list_con}>
          {/*<div className={styles.list_wrap}>
            {list.map((item: any) => {
              return (
                <div key={item.detail_url_alias} className={styles.list_item}>
                  <Image width={241} height={161}  src={item.thuimg324} alt={item.res_name}/>
                  <p className={styles.list_info}>
                    <span>{item.res_name}</span>
                    <span>{item.res_price}下载币</span>
                  </p>
                </div>
              )
            })}
          </div>*/}
          {
            data.length &&
            <WindowScroller>
              {({height, isScrolling, onChildScroll, scrollTop}) => (
                <Grid
                  autoHeight
                  isScrolling={isScrolling}
                  onScroll={onChildScroll}
                  scrollTop={scrollTop}
                  cellRenderer={cellRenderer}
                  columnCount={data[0].length}
                  columnWidth={240}
                  height={1000}
                  rowCount={data.length}
                  rowHeight={220}
                  width={1200}>
                </Grid>
              )}
            </WindowScroller>
          }
        </div>
      </main>
    </>
  )
}

export const getServerSideProps = async (ctx: any) => {
  const result = await getList()

  return {
    props: {
      ...result
    }
  }
}
